### ISSUE TITLE
Plugin error on build

### ISSUE THREAD

**Issue by ruiaraujo012** [l-mbert/vite-plugin-react-remove-attributes#2]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/16304685/174134983-98265931-5020-403c-af62-4988c75fd1f0.png">

**Comment by feslima** [comment]
@ruiaraujo012 Maybe one of these 2 solutions may work for you:
1. Add the `"ES2021.String"` value to `lib` param in `compilerOptions` of your `tsconfig.json` file.
2. Reuse/copy the plugin source code (it's small anyway) in your `vite.config.ts` and replace the [`replaceAll` call](https://github.com/l-mbert/vite-plugin-react-remove-attributes/blob/07f0b55d14ed461211e1ebbfc4fedf2e3abcb1c8/src/index.ts#L15) with `replace` (the regex used already has a global flag `g` set anyway).

**Comment by ruiaraujo012** [comment]
@feslima thank you. I will try that.

**Comment by l-mbert** [comment]
I replaced "replaceAll" with "replace", should be Fixed.

**Comment by feslima** [comment]
Hey @l-mbert do you plan to maintain the plugin? If you don't mind I would like to open a PR with some improvements that would solve this issue #1 as well.

**Comment by l-mbert** [comment]
> Hey @l-mbert do you plan to maintain the plugin? If you don't mind I would like to open a PR with some improvements that would solve this issue #1 as well.

I would greatly appreciate any PRs!
